set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
set(CMAKE_OBJC_COMPILER /usr/bin/clang)
set(CMAKE_OBJCXX_COMPILER /usr/bin/clang++)
# Flags exported for another toolchain (e.g. Homebrew LLVM) must not leak into AppleClang builds.
foreach(var CPPFLAGS CFLAGS CXXFLAGS LDFLAGS)
    if(DEFINED ENV{${var}} AND "$ENV{${var}}" MATCHES "homebrew/opt/llvm")
        set(ENV{${var}} "")
    endif()
endforeach()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES _VCPKG_ROOT_DIR)
include("${_VCPKG_ROOT_DIR}/scripts/toolchains/osx.cmake" OPTIONAL RESULT_VARIABLE _ox_osx)
if(NOT _ox_osx)
    include("$ENV{VCPKG_ROOT}/scripts/toolchains/osx.cmake")
endif()
