# Builds a tiny project from the legacy sample assets (copied, never modified), packs it and checks the output.
file(REMOVE_RECURSE ${WORK_DIR})
file(MAKE_DIRECTORY ${WORK_DIR}/Project/Assets/Models ${WORK_DIR}/Project/Assets/Scripts)
file(COPY ${LEGACY}/cube.obj ${LEGACY}/cube.mtl DESTINATION ${WORK_DIR}/Project/Assets/Models)
file(COPY ${LEGACY}/fiit.jpg DESTINATION ${WORK_DIR}/Project/Assets)
file(WRITE ${WORK_DIR}/Project/Assets/Scripts/main.lua "print('packed')\n")

execute_process(COMMAND ${OXPACK} ${WORK_DIR}/Project -o ${WORK_DIR}/Game.oxpak --verify
                RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
message("${out}")
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "oxpack failed (${rc}): ${err}")
endif()
if(NOT EXISTS ${WORK_DIR}/Game.oxpak)
    message(FATAL_ERROR "Game.oxpak was not written")
endif()
foreach(expect "Models/cube.obj" "Scripts/main.lua" "fiit.jpg" "verify: ok")
    string(FIND "${out}" "${expect}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "oxpack output lacks '${expect}'")
    endif()
endforeach()
if(NOT EXISTS ${WORK_DIR}/Project/Assets/Models/cube.obj.meta)
    message(FATAL_ERROR "metas were not created")
endif()

# Loose UI/data files travel verbatim; a patch pak only carries what changed.
file(MAKE_DIRECTORY ${WORK_DIR}/Project/Assets/UI)
file(WRITE ${WORK_DIR}/Project/Assets/UI/menu.rml "<rml><body>menu</body></rml>\n")
file(WRITE ${WORK_DIR}/Project/Assets/UI/menu.rcss "body { color: white; }\n")
file(WRITE ${WORK_DIR}/Project/Assets/UI/strings.json "{\"title\": \"Oxwald\"}\n")
execute_process(COMMAND ${OXPACK} ${WORK_DIR}/Project -o ${WORK_DIR}/Base.oxpak --verify
                RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "oxpack (loose files) failed (${rc}): ${err}")
endif()
foreach(expect "loose" "Assets/UI/menu.rml" "Assets/UI/menu.rcss" "Assets/UI/strings.json")
    string(FIND "${out}" "${expect}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "oxpack output lacks loose file '${expect}':\n${out}")
    endif()
endforeach()
file(WRITE ${WORK_DIR}/Project/Assets/UI/strings.json "{\"title\": \"Oxwald 1.1\"}\n")
execute_process(COMMAND ${OXPACK} ${WORK_DIR}/Project -o ${WORK_DIR}/Patch.oxpak --patch ${WORK_DIR}/Base.oxpak --verify
                RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "oxpack --patch failed (${rc}): ${err}")
endif()
string(FIND "${out}" "Assets/UI/strings.json" pos)
if(pos EQUAL -1)
    message(FATAL_ERROR "patch lacks the changed file:\n${out}")
endif()
foreach(unexpected "Assets/UI/menu.rml" "Models/cube.obj")
    string(FIND "${out}" "${unexpected}" pos)
    if(NOT pos EQUAL -1)
        message(FATAL_ERROR "patch contains unchanged '${unexpected}':\n${out}")
    endif()
endforeach()
string(FIND "${out}" "unchanged entries left out" pos)
if(pos EQUAL -1)
    message(FATAL_ERROR "patch summary missing:\n${out}")
endif()
