# Builds a tiny project from the legacy sample assets (copied, never modified), packs it and checks the output.
file(REMOVE_RECURSE ${WORK_DIR})
file(MAKE_DIRECTORY ${WORK_DIR}/Project/Assets/Models ${WORK_DIR}/Project/Assets/Scripts)
file(COPY ${LEGACY}/cube.obj ${LEGACY}/cube.mtl DESTINATION ${WORK_DIR}/Project/Assets/Models)
file(COPY ${LEGACY}/fiit.jpg DESTINATION ${WORK_DIR}/Project/Assets)
file(WRITE ${WORK_DIR}/Project/Assets/Scripts/main.lua "print('packed')\n")

execute_process(COMMAND ${OXPACK} ${WORK_DIR}/Project -o ${WORK_DIR}/Game.oxpak --verify
                RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
message("${out}")
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "oxpack failed (${rc}): ${err}")
endif()
if(NOT EXISTS ${WORK_DIR}/Game.oxpak)
    message(FATAL_ERROR "Game.oxpak was not written")
endif()
foreach(expect "Models/cube.obj" "Scripts/main.lua" "fiit.jpg" "verify: ok")
    string(FIND "${out}" "${expect}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "oxpack output lacks '${expect}'")
    endif()
endforeach()
if(NOT EXISTS ${WORK_DIR}/Project/Assets/Models/cube.obj.meta)
    message(FATAL_ERROR "metas were not created")
endif()
