//
// Created by ivanl on 21.09.2024.
//

#ifndef DESENGINE_DESENGINE_INCLUDE_CLASSES_GROUPOBJECT_HPP_
#define DESENGINE_DESENGINE_INCLUDE_CLASSES_GROUPOBJECT_HPP_

namespace DesEngine
{

	class GroupObject
	{

	};

} // DesEngine

#endif //DESENGINE_DESENGINE_INCLUDE_CLASSES_GROUPOBJECT_HPP_
