//
// Created by ivanl on 21.09.2024.
//

#ifndef DESENGINE_DESENGINE_INCLUDE_CLASSES_MESHOBJECT_HPP_
#define DESENGINE_DESENGINE_INCLUDE_CLASSES_MESHOBJECT_HPP_

namespace DesEngine
{

	class MeshObject
	{

	};

} // DesEngine

#endif //DESENGINE_DESENGINE_INCLUDE_CLASSES_MESHOBJECT_HPP_
