//
// Created by ivanl on 21.09.2024.
//

#ifndef DESENGINE_DESENGINE_INCLUDE_INTERFACES_PHYSICABLE_HPP_
#define DESENGINE_DESENGINE_INCLUDE_INTERFACES_PHYSICABLE_HPP_

#endif //DESENGINE_DESENGINE_INCLUDE_INTERFACES_PHYSICABLE_HPP_
